// Chinese landing pages for Chinese cross-border sellers. Every capability claim
// must stay inside seo/product-capabilities.md; the English page with the same
// slug (without the zh/ prefix) is the hreflang alternate.

export const zhPages = [
  {
    slug: 'zh/worten-repricer', theme: 'theme-worten', code: 'W.', codeNote: 'PT / ES<br>OFFER',
    title: 'Worten 自动调价软件｜自动跟价抢购物车 - 调价先锋',
    description: 'Worten 自动调价：按西班牙、葡萄牙渠道读取跟卖价格和运费，在最低价、最高价之间自动跟价，拿到购物车后尝试涨价。¥168/店铺/月，商品不限，免费试用 7 天。',
    keywords: 'Worten自动调价,Worten调价软件,Worten跟价,Worten购物车,Worten改价工具',
    eyebrow: 'Worten 自动调价 / 跨境卖家', crumb: 'Worten 自动调价',
    h1: 'Worten 自动调价：跟价、抢购物车、守住最低价',
    intro: '调价先锋读取 Worten 店铺 Offer 和当前可见的跟卖报价，按你设置的跟价差值自动调整价格，永远不低于最低价、不高于最高价。拿到购物车后可以按策略尝试调涨，不必一直停在最低价。每次调价是“已提交”还是“平台已确认”，都分开记录。',
    signalTitle: 'Worten Offer 调价流程', signalStatus: '规则驱动',
    signals: [['同步 Offer', '店铺、SKU、渠道', '精确匹配'], ['跟卖报价', '价格 + 运费 + 站点', '每轮读取'], ['调价决策', '最低价 / 最高价 / 差值', '边界保护'], ['执行结果', '提交与平台确认', '分开记录']],
    problemKicker: 'Worten 卖家常见问题', problemTitle: '手动改价跟不上，自动改价又怕亏',
    problemCopy: 'Worten 的跟卖价格随时在变，西班牙站和葡萄牙站的竞争情况也不一样。手动改价费时，简单粗暴的“比最低价再低 0.01”又容易把利润让光。',
    pains: [
      ['01 / 跟卖', '跟卖一改价，购物车就丢了', '竞争对手随时调价，靠人工盯后台很难及时响应，尤其是 SKU 多、店铺多的时候。'],
      ['02 / 站点', '只看商品价，容易跟错价', 'Worten 的竞争要看商品价加运费，而且西班牙、葡萄牙两个渠道的跟卖可能完全不同。'],
      ['03 / 结果', '改了价，却不知道有没有生效', '接口返回成功不等于前台价格已更新。没有记录，出了问题也很难排查。']
    ],
    mechanicsTitle: '调价先锋如何为 Worten 自动调价',
    mechanics: [
      ['识别 Offer', '按店铺、Offer SKU、EAN 和渠道精确匹配，不靠列表位置或相似商品猜测。'],
      ['读取竞争', '分渠道读取当前可见的跟卖店铺、商品价、运费和总价。'],
      ['计算目标价', '按设置的调价差值计算，结果必须落在最低价和最高价之间；拿到购物车后可按策略尝试调涨。'],
      ['追踪结果', '记录计算、提交、平台确认、触发保护和失败原因，方便运营复查。']
    ],
    shot: { src: '/doc-images/autopricy-workspace-mobile.webp', width: 900, height: 801, alt: '调价先锋 Offer 详情：分别展示西班牙和葡萄牙站点的跟卖店铺、店铺等级、商品价格、运费和总价', caption: '真实产品界面：同一个 Offer 在西班牙、葡萄牙站点的跟卖店铺、运费和总价分开展示。' },
    noteTitle: '价格是抢购物车的重要因素，但不是唯一因素',
    note: '根据 Worten 公开的排序规则，购物车（Winning Offer）会综合价格加运费，以及店铺表现等因素。调价先锋帮你让价格保持竞争力，但不承诺一定拿到购物车；库存、时效和店铺评分同样重要。',
    workflowTitle: '四步开始 Worten 自动调价',
    workflow: [['授权店铺', '使用 Worten 提供的 API 授权信息接入，不需要后台登录密码。'], ['同步 Offer', '检查 SKU、当前价格、跟卖情况和同步状态。'], ['设置规则', '为商品设置最低价、最高价、跟价差值和是否自动涨价，支持表格批量导入。'], ['查看结果', '先小范围运行，确认提交和平台确认都正常后再扩大范围。']],
    exampleTitle: '一条带底价保护的 Worten 调价规则', exampleLabel: '示例规则，非效果承诺',
    example: '<strong>示例：</strong>某 Offer 最低价 €15.00、最高价 €24.97、调价差值 €0.01。西班牙站最低跟卖总价为 €19.84 时，目标价为 €19.83，在区间内可以提交；如果跟卖降到 €14.90，目标价 €14.89 会被最低价拦截，系统不会跌破 €15.00。',
    sources: [['Worten 平台排序规则（Política digital）', 'https://www.worten.pt/politica-digital']],
    faq: [
      ['Worten 自动调价会低于我设置的最低价吗？', '不会。每次计算出的目标价都必须落在最低价和最高价之间；最低价缺失或设置无效时，该商品不会自动调价。'],
      ['西班牙站和葡萄牙站可以分别跟价吗？', '可以按渠道分别读取跟卖报价并提交对应渠道的价格。具体可用渠道以店铺实际开通情况为准，接入时会一起确认。'],
      ['需要提供 Worten 后台账号和密码吗？', '不需要。店铺通过 Worten 平台的 API 授权信息接入，不需要卖家后台登录密码。'],
      ['调价后多久生效？', '取决于 Worten 平台处理速度和接口限制。调价先锋会把“已提交”和“平台已确认”分开显示，不把请求成功当成已生效。'],
      ['用了自动调价就一定能拿到购物车吗？', '不能保证。价格只是购物车的因素之一，运费、库存、时效和店铺表现也会影响结果。']
    ],
    related: [['Mirakl 平台自动调价', '/zh/mirakl-repricer/'], ['最低价保护', '/zh/features/min-max-price-rules/'], ['多店铺批量调价', '/zh/features/multi-store-management/']]
  },
  {
    slug: 'zh/fnac-repricer', theme: 'theme-fnac', code: 'F.', codeNote: 'XML 2.6<br>OFFER',
    title: 'FNAC 自动调价软件｜Fnac 跟价改价工具 - 调价先锋',
    description: 'FNAC 自动调价：通过 Fnac XML 接口同步 Offer，排除自己店铺后对比跟卖价格和运费，在价格区间内批量改价并追踪批次结果。¥168/店铺/月，免费试用 7 天。',
    keywords: 'FNAC自动调价,Fnac调价软件,Fnac跟价,Fnac改价,法国Fnac调价工具',
    eyebrow: 'FNAC 自动调价 / 法国站卖家', crumb: 'FNAC 自动调价',
    h1: 'FNAC 自动调价：对比跟卖，批量改价，批次结果看得见',
    intro: '调价先锋通过 Fnac 的 XML 2.6 接口同步店铺 Offer，在排除你自己店铺之后对比其他卖家的报价和运费，按规则计算目标价，再分批提交更新。批次是“处理中”还是“已确认”，每一步都有记录。',
    signalTitle: 'FNAC XML Offer 流程', signalStatus: '批次感知',
    signals: [['同步', 'Offer 与卖家信息', 'XML 接口'], ['对比', '商品价 + 运费', '排除自己'], ['改价', '区间内目标价', '批量提交'], ['结果', '批次处理状态', '持续追踪']],
    problemKicker: 'FNAC 卖家常见问题', problemTitle: 'Fnac 改价不是改一个数字那么简单',
    problemCopy: 'Fnac 走的是 XML 批量接口，改价请求提交后要等批次处理；同时竞争对比要排除自己店铺、考虑运费，否则很容易“自己跟自己降价”。',
    pains: [
      ['01 / 自己', '不小心跟自己的报价竞争', '对比跟卖时必须正确排除当前店铺，否则规则会一路把自己的价格往下压。'],
      ['02 / 运费', '只看商品价不够', '买家看到的是商品价加运费，比较时要把可用的运费信息一起算进去。'],
      ['03 / 批次', '提交成功不等于价格已更新', 'XML 批次需要平台处理，处理完成前不能当成改价成功。']
    ],
    mechanicsTitle: '调价先锋如何为 FNAC 自动调价',
    mechanics: [['同步 Offer', '同步 Fnac 店铺的 Offer、SKU、卖家身份和当前可见的其他卖家报价。'], ['资格检查', '最低价、最高价有效且平台数据可用，才会计算目标价。'], ['XML 提交', '通过 Fnac XML 2.6 接口批量提交符合条件的改价。'], ['批次追踪', '轮询并记录批次结果；提交时不标记为已确认。']],
    noteTitle: 'FNAC 和 Darty 共用接口，但不共用竞争逻辑',
    note: 'Fnac 和 Darty 都使用 XML 2.6 接口，但店铺身份和跟卖对比逻辑是分开处理的。调价先锋不会把一个平台的结果直接套到另一个平台。',
    workflowTitle: '四步开始 FNAC 自动调价',
    workflow: [['接入店铺', '确认 Fnac 卖家账号和当前接口授权信息。'], ['检查 Offer', '核对 SKU、价格、运费、卖家身份和跟卖情况。'], ['设置区间', '为商品设置最低价、最高价和跟价差值，可批量导入。'], ['查看批次', '确认批次处理、确认和失败情况后，再扩大商品范围。']],
    exampleTitle: '一次 FNAC 批次改价的完整记录', exampleLabel: '示例流程',
    example: '<strong>示例：</strong>某商品价格区间为 €21.00–€27.00，系统根据其他卖家的报价计算出 €23.49 并加入 XML 批次。调价先锋先记录为“已提交”，等批次结果返回后才标记为已确认；批次报错时会显示失败原因。',
    sources: [['Fnac 平台排序规则', 'https://www.fnac.com/referencement-criteres-classement-marketplace']],
    faq: [
      ['Fnac 自动调价会和我自己的报价竞争吗？', '不会。对比跟卖时会排除当前店铺，只用其他卖家的可见报价计算目标价。'],
      ['会把运费算进去吗？', '会使用 Fnac Offer 数据中可用的运费信息进行比较，不会凭空估算缺失的运费。'],
      ['XML 提交成功是不是价格就改好了？', '不是。XML 批次还需要平台处理，调价先锋会分别显示提交和批次确认状态。'],
      ['FNAC 和 Darty 可以放在一个后台管理吗？', '可以。两个平台的店铺都能在同一个工作台里管理，但各自的店铺身份和竞争逻辑独立处理。']
    ],
    related: [['Darty 自动调价', '/zh/darty-repricer/'], ['最低价保护', '/zh/features/min-max-price-rules/'], ['欧洲多平台自动调价', '/zh/multi-marketplace-repricing/']]
  },
  {
    slug: 'zh/darty-repricer', theme: 'theme-darty', code: 'D.', codeNote: 'DARTY<br>OFFER',
    title: 'Darty 自动调价软件｜Darty 跟价改价工具 - 调价先锋',
    description: 'Darty 自动调价：独立处理 Darty 店铺身份和跟卖对比，在最低价、最高价之间自动跟价，XML 批量提交并追踪批次结果。¥168/店铺/月，商品不限，免费试用 7 天。',
    keywords: 'Darty自动调价,Darty调价软件,Darty跟价,Darty改价工具,法国Darty',
    eyebrow: 'Darty 自动调价 / 法国站卖家', crumb: 'Darty 自动调价',
    h1: 'Darty 自动调价：独立的跟卖对比，守住价格区间',
    intro: '调价先锋通过 Fnac/Darty 共用的 XML 2.6 接口为 Darty 店铺自动调价，同时保留 Darty 自己的店铺身份和跟卖对比逻辑。改价请求、批次处理和最终结果分开记录，不会混在一起。',
    signalTitle: 'Darty Offer 调价控制', signalStatus: 'Darty 专属',
    signals: [['店铺', 'Darty 账号身份', '独立'], ['竞争', '符合条件的跟卖', '筛选'], ['改价', 'XML 批次', '区间保护'], ['状态', '批次处理结果', '可见']],
    problemKicker: 'Darty 卖家常见问题', problemTitle: '接口和 Fnac 一样，竞争规则却不一样',
    problemCopy: '很多工具把 Darty 当成 Fnac 的附属，直接套用同一套对比逻辑。实际上店铺身份和跟卖筛选都需要按 Darty 单独处理。',
    pains: [
      ['01 / 账号', '改价必须落在正确的 Darty 店铺', '店铺授权和 Offer 身份只属于对应的 Darty 账号，不能和其他店铺混用。'],
      ['02 / 竞争', '跟卖筛选按平台区分', '使用 Darty 自己的跟卖处理逻辑，而不是照搬 Fnac 的卖家对比。'],
      ['03 / 处理', '批次处理需要时间', '提交、等待、平台确认和失败是不同阶段，后台会分别显示。']
    ],
    mechanicsTitle: '调价先锋如何为 Darty 自动调价',
    mechanics: [['同步', '读取 Darty Offer，保留店铺、SKU 和平台身份。'], ['对比', '只使用符合 Darty 当前规则的跟卖报价。'], ['约束', '目标价始终在卖家设置的最低价和最高价之间。'], ['确认', '通过 XML 提交后追踪批次结果，再报告最终状态。']],
    noteTitle: '不承诺一定拿到购物车',
    note: '调价先锋负责让符合条件的价格及时调整，但 Darty 的排序还会受到库存、配送、店铺表现和平台政策影响。',
    workflowTitle: '四步开始 Darty 自动调价',
    workflow: [['确认账号', '检查 Darty 店铺身份和授权方式。'], ['检查 Offer', '核对 SKU、当前价格、跟卖情况和状态。'], ['设置区间', '为一批商品设置最低价、最高价和跟价差值。'], ['观察批次', '批次处理和确认都正常后，再扩大调价范围。']],
    exampleTitle: 'Darty 改价在确认前保持“处理中”', exampleLabel: '示例流程',
    example: '<strong>示例：</strong>调价先锋在 €50.00–€62.00 区间内计算出 €54.90，并通过 XML 批次提交。在 Darty 返回批次结果前，这条改价显示为“已提交”或“处理中”，不会提前标记为成功。',
    faq: [
      ['Darty 和 Fnac 的调价逻辑完全一样吗？', '不一样。两者共用 XML 接口，但店铺类型、店铺身份和跟卖处理是分开的。'],
      ['Darty 自动调价会一直降到最低吗？', '不会。目标价由你设置的规则和价格区间决定，目的不是无限降价。'],
      ['已经提交的 Darty 改价还会失败吗？', '会。批次可能处理中或返回错误，所以确认状态会单独追踪。'],
      ['所有 Darty 店铺都能接入吗？', '接入前会先确认店铺账号和当前接口能力，确认可用后再开启自动调价。']
    ],
    related: [['FNAC 自动调价', '/zh/fnac-repricer/'], ['自动调价原理', '/zh/features/automatic-repricing/'], ['欧洲多平台自动调价', '/zh/multi-marketplace-repricing/']]
  },
  {
    slug: 'zh/onbuy-repricer', theme: 'theme-onbuy', code: 'O.', codeNote: 'UK<br>LISTING',
    title: 'OnBuy 自动调价软件｜抢购物车、赢后自动涨价 - 调价先锋',
    description: 'OnBuy 自动调价：同步 Product 和 Listing，检查是否赢得购物车，没赢时在底价之上跟价，赢了之后按策略尝试涨价。¥168/店铺/月，商品不限，免费试用 7 天。',
    keywords: 'OnBuy自动调价,OnBuy调价软件,OnBuy跟价,OnBuy购物车,OnBuy Winning Offer,英国OnBuy',
    eyebrow: 'OnBuy 自动调价 / 英国站卖家', crumb: 'OnBuy 自动调价',
    h1: 'OnBuy 自动调价：该降就降，赢了就涨',
    intro: '调价先锋把 OnBuy 的 Product 和 Listing 数据接入调价规则：先判断 Listing 当前是否赢得购物车（Winning Offer），没赢时在最低价之上跟价，赢了之后按策略小幅尝试涨价，始终不超过最高价。',
    signalTitle: 'OnBuy 购物车调价循环', signalStatus: '配额感知',
    signals: [['商品', 'Product 与 Listing', '分开处理'], ['状态', '是否赢得购物车', '每轮检查'], ['动作', '跟价降价 / 赢后涨价', '区间保护'], ['结果', '排队与确认状态', '历史记录']],
    problemKicker: 'OnBuy 卖家常见问题', problemTitle: '只会降价的调价工具，在 OnBuy 上会把利润打光',
    problemCopy: '好的 OnBuy 调价不应该每一轮都降价。它需要区分 Product 和 Listing，判断是否已经赢得购物车，还要处理接口配额和改价延迟。',
    pains: [
      ['01 / 对象', 'Product 和 Listing 不是一回事', '调价先锋把商品目录和可售 Listing 分开处理，确保改价落在正确的 Listing 上。'],
      ['02 / 方向', '赢没赢，下一步完全不同', '没赢时需要在底价之上跟价；已经赢了，可以按策略谨慎涨价，而不是继续降。'],
      ['03 / 延迟', '前台价格会比提交晚', 'OnBuy 的改价有排队和展示延迟，调价先锋记录排队和后续状态，不承诺立即生效。']
    ],
    mechanicsTitle: '调价先锋如何为 OnBuy 自动调价',
    mechanics: [['同步', '读取 Product 和 Listing，保留账号和 Listing 身份。'], ['检查', '使用当前可用的购物车状态和竞争信息。'], ['决策', '在最低价和最高价之间执行降价跟价或赢后涨价策略。'], ['确认', '处理锁、配额和延迟，保存每次调价的状态历史。']],
    shot: { src: '/doc-images/autopricy-workspace-desktop.webp', width: 1440, height: 1008, alt: '调价先锋 OnBuy 店铺工作台：调价次数、购物车占比、开启调价商品数、每轮调价耗时和 Listing 筛选', caption: '真实产品界面：OnBuy 店铺工作台，集中查看调价次数、购物车占比、每轮调价耗时和 Listing 列表。' },
    noteTitle: '购物车不只由价格决定',
    note: '调价先锋根据接口可获取的 OnBuy 信息做出反应。库存、配送、店铺表现和平台规则仍然会影响哪个卖家赢得购物车。',
    workflowTitle: '四步开始 OnBuy 自动调价',
    workflow: [['授权账号', '确认当前 OnBuy 授权方式和店铺信息。'], ['同步商品', '同步 Product 和 Listing，检查价格、库存和购物车状态。'], ['设置两条边界', '设置最低价、最高价、跟价差值和是否赢后涨价。'], ['观察结果', '查看排队、配额处理和平台确认后再扩大范围。']],
    exampleTitle: '赢得购物车后的受控涨价', exampleLabel: '示例策略',
    example: '<strong>示例：</strong>某 Listing 以 £31.20 赢得购物车，最低价 £28.00、最高价 £34.00。策略可以尝试 £31.40；如果之后失去购物车，下一轮会在区间内重新跟价，但不会超过 £34.00，也不会假设前台立即更新。',
    sources: [['OnBuy API 文档', 'https://docs.api.onbuy.com/'], ['OnBuy 卖家条款', 'https://cdn.onbuy.com/static/pdf/seller-terms/Seller%20Terms%20v3.0.0.pdf']],
    faq: [
      ['OnBuy 赢得购物车后可以自动涨价吗？', '可以。在当前购物车状态支持的情况下，策略可以小幅尝试涨价，最高价始终是硬上限。'],
      ['OnBuy 改价是立即生效的吗？', '不一定。平台有排队和展示延迟，调价先锋会把提交和后续确认分开记录。'],
      ['最低价就一定能拿到 OnBuy 购物车吗？', '不一定。价格很重要，但库存、配送、店铺表现和平台规则也会影响结果。'],
      ['会不会出现重复或冲突的改价？', '系统使用锁、配额感知的调度和状态历史，尽量避免同一 Listing 同时执行多个改价任务。']
    ],
    related: [['最低价保护', '/zh/features/min-max-price-rules/'], ['多店铺批量调价', '/zh/features/multi-store-management/'], ['欧洲多平台自动调价', '/zh/multi-marketplace-repricing/']]
  },
  {
    slug: 'zh/cdiscount-repricer', theme: 'theme-cdiscount', code: 'C.', codeNote: 'OCTOPIA<br>OFFER',
    title: 'Cdiscount 自动调价软件｜多店铺批量跟价 - 调价先锋',
    description: 'Cdiscount 自动调价：OAuth 授权接入，批量导入调价规则，最低价、最高价保护，记录 Package 反馈和改价回读结果，多店铺统一管理。¥168/店铺/月，免费试用 7 天。',
    keywords: 'Cdiscount自动调价,Cdiscount调价软件,Cdiscount跟价,Cdiscount购物车,Octopia调价',
    eyebrow: 'Cdiscount 自动调价 / 法国站卖家', crumb: 'Cdiscount 自动调价',
    h1: 'Cdiscount 自动调价：批量规则、底价保护、结果可回读',
    intro: '调价先锋通过当前的 OAuth 和 SellerId 方式接入 Cdiscount 店铺，同步 Product 和 Offer，批量导入调价规则，在价格区间内自动跟价，并记录 Package 反馈和之后的平台回读结果。适合需要多店铺统一管理、想看清每次调价结果的卖家。',
    signalTitle: 'Cdiscount 调价执行链', signalStatus: '反馈感知',
    signals: [['接入', 'OAuth 与 SellerId', '按店铺隔离'], ['规则', '商品价格区间', '校验'], ['Package', '改价反馈', '记录'], ['回读', '平台最新状态', '核对']],
    problemKicker: 'Cdiscount 卖家常见问题', problemTitle: '平台自带底价功能，为什么还要外部调价？',
    problemCopy: 'Cdiscount 本身提供底价相关功能。外部调价工具的价值在于：多店铺统一规则、批量操作，以及每次改价都能查到反馈和最终结果。',
    pains: [
      ['01 / 授权', '授权和 SellerId 必须对应', '调价先锋把授权和改价操作限定在对应的 Cdiscount 卖家账号内。'],
      ['02 / 反馈', 'Package 接收只是中间状态', 'Package 反馈可能是处理中或报错，不能简单当成“改价成功”。'],
      ['03 / 冲突', '平台功能和外部工具可能打架', '开启前要确认谁负责调价，避免两个系统同时改同一个 Offer。']
    ],
    mechanicsTitle: '调价先锋如何为 Cdiscount 自动调价',
    mechanics: [['接入', '使用当前的 OAuth 和 SellerId 流程授权卖家账号。'], ['导入规则', '为精确的商品设置最低价、最高价和调价参数，支持表格导入。'], ['提交 Package', '提交符合条件的 Offer 改价，保存 Package 和商品级反馈。'], ['回读核对', '之后读取平台最新价格，与目标价对比后才标记为已确认。']],
    shot: { src: '/doc-images/autopricy-cdiscount-workspace.webp', width: 1440, height: 1188, alt: '调价先锋 Cdiscount 店铺工作台：Offer 总数、开启调价商品数、购物车占比、调价次数，以及最低价、最高价、调价差值和调价状态', caption: '真实产品界面：Cdiscount 店铺工作台，Offer 的当前价格、购物车价格、最高价、最低价和调价状态一屏可见。' },
    noteTitle: '外部调价不应该和平台功能互相冲突',
    note: 'Cdiscount 自带的底价机制可能已经在某些 Offer 上运行。开启调价先锋前，请先确认由哪个系统负责价格决策，避免重复自动化。',
    workflowTitle: '四步开始 Cdiscount 自动调价',
    workflow: [['授权店铺', '确认 OAuth、SellerId 和店铺信息。'], ['检查现有自动化', '确认是否已有平台底价设置或其他工具在改价。'], ['导入规则', '校验商品身份、最低价、最高价和适用范围。'], ['追踪反馈', '查看 Package 反馈、报错和回读结果后再扩大范围。']],
    exampleTitle: 'Package 反馈不等于最终价格', exampleLabel: '示例流程',
    example: '<strong>示例：</strong>目标价 €19.80 在 €18.50–€24.00 区间内，进入 Offer Package。调价先锋先记录 Package 和商品反馈，再核对平台之后的实际价格；仅有 Package 处理成功，不会被描述为已拿到购物车。',
    sources: [['Cdiscount 卖家指南：平台底价功能', 'https://marketplace.cdiscount.com/en/bien-preparer-les-temps-forts-commerciaux/']],
    faq: [
      ['调价先锋和 Cdiscount 自带的调价有什么区别？', '调价先锋侧重多店铺统一规则、批量操作、Package 反馈和执行记录。用哪个取决于你当前的店铺设置。'],
      ['平台自带调价和外部调价能同时开吗？', '不建议。两个系统同时改价可能互相冲突，开启前请先确定由谁负责。'],
      ['Package 成功是不是前台价格就改好了？', '不一定。Package 反馈和之后的平台回读是两份不同的证据，调价先锋会分别记录。'],
      ['可以同时管理多个 Cdiscount 店铺吗？', '可以。每个店铺单独授权，在同一个工作台里筛选、批量设置规则和查看结果。']
    ],
    related: [['多店铺批量调价', '/zh/features/multi-store-management/'], ['自动调价原理', '/zh/features/automatic-repricing/'], ['FNAC 自动调价', '/zh/fnac-repricer/']]
  },
  {
    slug: 'zh/mirakl-repricer', theme: 'theme-multi', code: 'M.', codeNote: 'SELECTED<br>OPERATORS',
    title: 'Mirakl 平台自动调价｜按平台评估的跟价工具 - 调价先锋',
    description: 'Mirakl 平台自动调价：Worten 等基于 Mirakl 的欧洲平台，按平台实际开放的数据和渠道自动跟价，最低价、最高价保护，改价结果可追踪。免费试用 7 天。',
    keywords: 'Mirakl自动调价,Mirakl调价软件,Mirakl平台跟价,Mirakl店铺改价',
    eyebrow: 'Mirakl 平台自动调价 / 已评估平台', crumb: 'Mirakl 平台自动调价',
    h1: 'Mirakl 平台自动调价：按平台评估，不搞一刀切',
    intro: 'Worten 等很多欧洲平台基于 Mirakl 搭建，但每个平台开放的 Offer 字段、跟卖数据、渠道和接口限制都不一样。调价先锋为经过评估的 Mirakl 平台提供自动调价，按平台实际能力处理，不承诺“所有 Mirakl 平台通用”。',
    signalTitle: '按平台适配的调价循环', signalStatus: '逐个渠道评估',
    signals: [['Offer 数据', '平台实际开放的字段', '先验证'], ['价格边界', '最低价 / 最高价', '硬限制'], ['渠道改价', '符合条件的价格更新', '规则驱动'], ['平台结果', '提交 / 确认', '追踪']],
    problemKicker: '为什么 Mirakl 调价因平台而异', problemTitle: '底层系统一样，平台规则不一样',
    problemCopy: 'Mirakl 只是平台的技术底座。每个平台自己决定开放哪些 Offer 字段、跟卖信息、渠道、频率限制和改价方式。',
    pains: [
      ['01 / 平台', '能力因平台而异', '一个平台能用的字段或操作，换一个平台不一定有。调价先锋在开启前先检查目标平台。'],
      ['02 / 身份', 'Offer 必须精确匹配', '改价始终对应真实的店铺、SKU、商品和渠道，不按位置、价格或相似商品猜测。'],
      ['03 / 状态', '接口接收不等于已生效', '提交、平台处理、确认和失败是不同状态，分开记录。']
    ],
    mechanicsTitle: '已评估的 Mirakl 平台如何自动调价',
    mechanics: [['市场数据', '只使用该平台真正开放的 Offer 和跟卖数据。'], ['决策', '在 Offer 的最低价和最高价之间执行调价规则。'], ['提交', '按平台对应的接口和渠道提交符合条件的改价。'], ['验证', '在平台返回结果或回读确认之前，保持“处理中”状态。']],
    noteTitle: '已评估的平台，而不是“所有 Mirakl 平台”',
    note: '接入前我们会确认平台、国家、授权方式、Offer 数据、跟卖可见性、改价方式和确认机制。平台不支持的字段，不会用通用假设去填补。',
    workflowTitle: '先验证一个平台，再扩大范围',
    workflow: [['说明平台', '告诉我们平台名称、国家、店铺数、SKU 数量和当前改价方式。'], ['确认接口范围', '检查授权、Offer 字段、跟卖可见性、渠道和限制。'], ['小范围核对', '核对商品身份、当前价格、价格区间和可用的市场数据。'], ['开启并观察', '先用带边界的规则运行，看到平台结果后再扩大。']],
    exampleTitle: '一条以价格边界为先的 Mirakl 规则', exampleLabel: '示例规则，非效果承诺',
    example: '<strong>示例：</strong>某 Offer 最低价 €24.00、最高价 €32.00。如果平台开放了可比的跟卖报价 €26.50，规则可以把目标价定为 €26.49；如果平台没有开放所需数据，或改价无法确认，系统不会假装价格已经生效。',
    sources: [['Mirakl Offer API 文档', 'https://developer.mirakl.com/content/product/mmp/rest/operator/openapi3/offers']],
    faq: [
      ['调价先锋支持所有 Mirakl 平台吗？', '不是。每个平台的数据、渠道、频率限制和允许的操作不同，需要逐个评估。目前公开支持 Worten，其他平台请联系我们确认。'],
      ['Mirakl 自动调价和价格同步是一回事吗？', '不是。价格同步只是复制一个价格；自动调价还需要跟卖数据、调价规则、价格边界、提交和结果验证。'],
      ['会低于我设置的最低价吗？', '不会。目标价被限制在最低价和最高价之间，边界缺失或无效时不会自动调价。'],
      ['最低价就能拿到购物车吗？', '不一定。库存、配送、店铺表现和平台规则同样影响排序。']
    ],
    related: [['Worten 自动调价', '/zh/worten-repricer/'], ['欧洲多平台自动调价', '/zh/multi-marketplace-repricing/'], ['自动调价原理', '/zh/features/automatic-repricing/']]
  },
  {
    slug: 'zh/multi-marketplace-repricing', theme: 'theme-multi', code: '∞', codeNote: 'STORES<br>CHANNELS',
    title: '欧洲电商平台自动调价软件｜多平台跟价 - 调价先锋',
    description: '面向中国跨境卖家的欧洲平台自动调价软件，一个后台管理 Worten、FNAC、Darty、OnBuy、Cdiscount 和部分 Mirakl 平台店铺，自动跟价、最低价保护、批量调价。',
    keywords: '欧洲平台自动调价,跨境电商调价软件,多平台调价,自动跟价软件,欧洲跟卖调价',
    eyebrow: '欧洲多平台自动调价 / 跨境卖家', crumb: '欧洲多平台自动调价',
    h1: '欧洲多平台自动调价：一个后台，各平台按自己的规则执行',
    intro: '调价先锋让跨境卖家在一个工作台里管理多个欧洲平台、多个店铺的调价规则和执行记录。界面统一，但授权、数据、跟卖对比、提交和确认都按平台分别处理，不会一刀切。',
    signalTitle: '统一管理，平台独立适配', signalStatus: '不做 ERP',
    signals: [['店铺', '授权按店铺隔离', '分开'], ['规则', '按 Offer 和平台', '有边界'], ['执行', '平台专属适配', '精确'], ['记录', '统一的操作视图', '可追溯']],
    problemKicker: '跨境卖家的调价难题', problemTitle: '统一管理，不能抹掉平台差异',
    problemCopy: '卖家想要一个后台看清所有店铺，但每个平台的购物车规则、跟卖数据、频率限制和改价方式都不一样。',
    pains: [
      ['01 / 店铺', '每个店铺的权限独立', '授权、商品身份、渠道和操作都限定在对应店铺内。'],
      ['02 / 规则', '同样的界面，不同的底层逻辑', '最低价、最高价、调价状态这些概念统一，平台差异由适配层处理。'],
      ['03 / 记录', '一套记录，状态真实', '计算、保护、提交、处理中、已确认、失败分开显示。']
    ],
    mechanicsTitle: '当前公开支持的调价平台',
    support: [['Worten', '成熟的 Offer 自动调价和平台确认流程，支持按渠道跟价。', '/zh/worten-repricer/'], ['FNAC', 'XML Offer 改价、排除自己的跟卖对比、批次追踪。', '/zh/fnac-repricer/'], ['Darty', '通过 XML 接口执行 Darty 专属的跟卖处理。', '/zh/darty-repricer/'], ['OnBuy', 'Product/Listing 同步、购物车检查、赢后涨价。', '/zh/onbuy-repricer/'], ['Cdiscount', 'OAuth 接入、批量规则、Package 反馈和回读。', '/zh/cdiscount-repricer/'], ['部分 Mirakl 平台', '逐个平台评估，不承诺全部通用。', '/zh/mirakl-repricer/']],
    noteTitle: '调价先锋不是 ERP',
    note: '核心是自动调价、跟卖监控、价格边界和多店铺 Offer 管理，另有商品采集、批量导入导出等辅助工具。不做订单、仓储、采购、财务和物流管理。Fyndiq 目前只提供 Article 价格和库存管理，不作为竞争型自动调价宣传。',
    workflowTitle: '增加平台，也不失控',
    workflow: [['梳理店铺', '列出每个平台、账号、国家、SKU 数量和当前谁负责改价。'], ['确认平台适配', '按平台确认可用数据、限制、商品身份和改价方式。'], ['设置安全规则', '配置价格边界和策略，店铺之间不共享授权和状态。'], ['统一看记录', '在一个视图里查找被保护、处理中、已确认和失败的调价。']],
    exampleTitle: '统一后台，不等于统一逻辑', exampleLabel: '运营示例',
    example: '<strong>示例：</strong>团队可以用同一套最低价/最高价流程管理 Worten、FNAC 和 OnBuy。底层上，Worten 走 Offer/渠道接口，FNAC 提交 XML 批次，OnBuy 检查 Product/Listing 和购物车状态。统一界面减少来回切换后台，但不会抹平这些差异。',
    faq: [
      ['调价先锋支持哪些欧洲平台？', '目前公开支持 Worten、FNAC、Darty、OnBuy、Cdiscount，以及经过评估的部分 Mirakl 平台，各平台页面写明了具体能力和限制。'],
      ['Fyndiq 可以自动调价吗？', 'Fyndiq 目前提供 Article 的价格、库存等批量管理，不作为基于跟卖的竞争型自动调价工具。'],
      ['怎么收费？', '自动调价标准版 168 元 / 店铺 / 月，商品数量不限；注册后自动开通 7 天免费试用。'],
      ['能管理订单和仓库吗？', '不能。调价先锋专注调价和 Offer 运营，不是订单、仓储、采购、财务或物流 ERP。']
    ],
    related: [['自动调价原理', '/zh/features/automatic-repricing/'], ['最低价保护', '/zh/features/min-max-price-rules/'], ['多店铺批量调价', '/zh/features/multi-store-management/']]
  },
  {
    slug: 'zh/features/automatic-repricing', theme: 'theme-multi', code: 'A.', codeNote: 'OBSERVE<br>VERIFY',
    title: '跨境电商自动调价与竞争跟价｜原理和做法 - 调价先锋',
    description: '自动调价和竞争调价怎么做？从读取跟卖价格、按规则计算目标价、守住最低价，到提交改价和确认生效，调价先锋把每一步都记录下来。免费试用 7 天。',
    keywords: '自动调价,竞争调价,自动跟价,跨境电商调价,调价软件',
    eyebrow: '产品能力 / 自动调价', crumb: '自动调价',
    h1: '自动调价不是一个改价按钮，而是一个闭环',
    intro: '调价先锋把自动调价拆成可以检查的几步：商品是否符合条件、读到了什么跟卖数据、为什么算出这个目标价、提交给了平台什么、平台最后返回了什么。每一步都留痕，出问题能查到原因。',
    signalTitle: '自动调价闭环', signalStatus: '每步留痕',
    signals: [['资格', '商品和规则是否有效', '先检查'], ['输入', '跟卖价格', '平台数据'], ['决策', '规则 + 价格边界', '可解释'], ['结果', '提交与确认', '记录']],
    problemKicker: '竞争调价的关键', problemTitle: '自动调价真正难的是“看得见”',
    problemCopy: '很多工具只告诉你“已改价”，但运营需要知道：为什么改、改成多少、平台有没有接受、前台是不是真的变了。',
    pains: [
      ['01 / 资格', '不是每个商品都该自动改价', '缺少最低价、规则无效或数据异常的商品，应该停下来，而不是乱改。'],
      ['02 / 依据', '每次改价都要有依据', '目标价来自哪条跟卖报价、哪条规则，都应该可以追溯。'],
      ['03 / 结果', '请求成功不等于已生效', '平台接收、处理中、已确认和失败要分开看。']
    ],
    mechanicsTitle: '一次自动调价经历的五个阶段',
    mechanics: [['资格检查', '确认店铺、商品、价格边界和规则都有效。'], ['读取输入', '使用平台开放的当前 Offer 和跟卖数据。'], ['计算目标', '按调价差值和策略计算，结果必须在最低价和最高价之间。'], ['提交改价', '通过平台接口提交符合条件的价格更新。'], ['确认结果', '根据平台反馈或回读结果标记已确认、处理中或失败。']],
    noteTitle: '自动化，不等于失控',
    note: '调价先锋的核心调价决策基于明确的规则和卖家设置的边界，不是让 AI 自己定价。缺少必要数据、任务被锁定、平台拒绝或无法确认时，系统会停下来或显示异常。',
    workflowTitle: '从观察到全面自动化',
    workflow: [['接入并同步', '先确认店铺和 Offer 数据准确，再创建规则。'], ['配置边界', '设置最低价、最高价和适合该平台的策略。'], ['小范围运行', '在少量商品上观察计算、保护和提交状态。'], ['确认后扩大', '平台结果和历史记录符合预期后，再推广到更多商品。']],
    exampleTitle: '自动调价什么时候应该停下来', exampleLabel: '控制示例',
    example: '<strong>示例：</strong>定时任务开始运行，找到一个有效 Offer，但这一轮没有读到跟卖数据。正确的结果不是猜一个价格，而是跳过并记录原因，保持平台上最后确认的价格不变。',
    faq: [
      ['自动调价和竞争调价有什么区别？', '竞争调价是根据跟卖价格变化来调整自己的价格，是自动调价最常见的用法。调价先锋会在价格边界内自动完成这个过程。'],
      ['多久调一次价？', '系统持续运行，按平台接口能力、店铺规模和当前配置定时检查和调价。'],
      ['调价是 AI 决定的吗？', '不是。核心调价使用明确的规则和价格边界，每次改价都可以解释原因。'],
      ['可以先拿几个商品试试吗？', '可以，也推荐这样做。先用少量商品验证商品身份、规则、提交和确认，再扩大范围。']
    ],
    related: [['最低价保护', '/zh/features/min-max-price-rules/'], ['多店铺批量调价', '/zh/features/multi-store-management/'], ['欧洲多平台自动调价', '/zh/multi-marketplace-repricing/']]
  },
  {
    slug: 'zh/features/min-max-price-rules', theme: 'theme-safety', code: '±', codeNote: 'PRICE<br>BOUNDARIES',
    title: '最低价保护｜自动调价不跌破底价 - 调价先锋',
    description: '为每个 Offer 设置最低价和最高价，自动调价只在区间内执行：跟卖降价时不会跌破底价，赢得购物车后涨价也不会超过上限。支持表格批量设置，免费试用 7 天。',
    keywords: '最低价保护,自动调价底价,调价最低价,最高价设置,跟价不亏本',
    eyebrow: '产品能力 / 价格边界', crumb: '最低价保护',
    h1: '最低价和最高价，是自动调价的硬边界',
    intro: '调价先锋只在你设置的最低价和最高价之间执行调价。边界绑定在真实的 Offer 上，并在后台清楚显示，跟卖再怎么降价，也不会把你的价格悄悄压到亏本。',
    signalTitle: 'Offer 价格护栏', signalStatus: '卖家设置',
    signals: [['底价', '允许的最低价', '硬性拦截'], ['上限', '允许的最高价', '硬性拦截'], ['目标价', '规则计算结果', '校验'], ['记录', '触发保护的决策', '可见']],
    problemKicker: '调价安全', problemTitle: '底价只有在校验和执行一致时才有用',
    problemCopy: '价格安全取决于商品身份是否正确、边界数值是否有效、计算路径和最终提交的价格是否一致，而不只是界面上的一个输入框。',
    pains: [
      ['01 / 有效性', '无效区间不能运行', '数值缺失、不是数字，或最低价高于最高价时，应该阻止开启自动调价。'],
      ['02 / 身份', '边界属于具体的 Offer', '规则绑定正确的店铺和 SKU，而不是按 EAN 或列表位置猜测。'],
      ['03 / 可见', '触发保护要看得到', '目标价越过边界时，后台会显示护栏拦截或调整了这次改价。']
    ],
    mechanicsTitle: '价格边界如何影响每一次调价',
    mechanics: [['校验', '要求数值有效，且最低价不高于最高价。'], ['计算', '使用平台的跟卖数据，按该平台的规则计算目标价。'], ['约束', '目标价超出区间时，按配置拦截或调整到边界。'], ['记录', '保存原因、目标价和最终动作，方便复查。']],
    shot: { src: '/doc-images/detail.png', width: 1146, height: 1528, alt: '调价先锋 Offer 详情：葡萄牙价格、西班牙价格、调价差值、最低价、最高价、是否自动涨价，以及西班牙站跟卖店铺列表', caption: '真实产品界面：每个 Offer 单独设置调价差值、最低价、最高价和是否自动涨价，下方是各站点的跟卖报价。' },
    noteTitle: '底价要反映你的真实成本',
    note: '调价先锋执行你设置的数值，不会自动计算真实利润。设置最低价时，请把平台佣金、税费、运费、促销和汇率等成本考虑进去。',
    workflowTitle: '开启自动调价前先设好边界',
    workflow: [['算出商业底价', '把店铺和商品相关的成本和利润要求算进去。'], ['设置合理上限', '决定赢得购物车后最多可以涨到多少。'], ['用真实 Offer 校验', '开启前核对店铺、SKU、币种和当前价格，可用表格批量导入。'], ['复查保护记录', '通过历史记录找到经常碰到底价或上限的商品。']],
    exampleTitle: '低于底价的目标价不会被提交', exampleLabel: '示例计算',
    example: '<strong>示例：</strong>某 Offer 最低价 €20.00、最高价 €28.00。跟价规则算出 €19.75 时，正确结果是触发保护，而不是提交 €19.75。是停在 €20.00 还是跳过本次改价，由适用的规则明确决定。',
    faq: [
      ['调价先锋会帮我算最低价吗？', '不会。最低价由卖家根据自己的成本设定，调价先锋负责校验并在自动调价中严格执行。'],
      ['最低价高于最高价会怎样？', '规则无效，修正区间之前不会开启自动调价。'],
      ['不同商品可以设置不同的价格区间吗？', '可以。边界绑定到具体店铺的 Offer，每个商品可以有自己的区间，也可以用表格批量设置。'],
      ['赢得购物车后一定会涨到最高价吗？', '不会。涨价取决于平台能力和配置的策略，最高价只是上限，不是目标。']
    ],
    related: [['自动调价原理', '/zh/features/automatic-repricing/'], ['OnBuy 赢后自动涨价', '/zh/onbuy-repricer/'], ['多店铺批量调价', '/zh/features/multi-store-management/']]
  },
  {
    slug: 'zh/features/multi-store-management', theme: 'theme-multi', code: 'N.', codeNote: 'SHOP-SCOPED<br>OPERATIONS',
    title: '多店铺批量调价｜一个后台管理多个欧洲店铺 - 调价先锋',
    description: '一个后台管理多个平台、多个店铺：按平台、店铺、EAN、SKU、价格区间和状态筛选，批量导入调价规则、批量改价和导出，每个店铺授权独立、记录可追溯。',
    keywords: '批量调价,多店铺调价,多店铺管理,批量改价,跨境多店铺',
    eyebrow: '产品能力 / 多店铺批量管理', crumb: '多店铺批量调价',
    h1: '多店铺批量调价：统一管理，权限不混',
    intro: '调价先锋把支持的店铺放在一个工作台里，但授权、商品身份、规则、任务和结果都限定在各自的店铺内。团队可以按条件筛选、批量操作，同时不会把一个店铺的操作误用到另一个店铺。',
    signalTitle: '按店铺隔离的工作台', signalStatus: '设计上隔离',
    signals: [['授权', '每个店铺独立', '隔离'], ['Offer', '精确到店铺', '限定'], ['批量', '筛选后的范围', '可控'], ['记录', '店铺与任务上下文', '可追溯']],
    problemKicker: '多店铺批量调价', problemTitle: '店铺越多，越要分清边界',
    problemCopy: '多个店铺放在一个后台时，每一次读取和改价仍然要对应正确的平台、账号、店铺、SKU 和规则。',
    pains: [
      ['01 / 权限', '授权不能跨店铺', '平台授权和店铺记录绑定，所有操作使用对应店铺的上下文。'],
      ['02 / 范围', '批量操作要有明确范围', '筛选条件、勾选的商品和任务记录清楚说明包含哪些店铺和 Offer。'],
      ['03 / 结果', '结果要细到店铺', '只看全局成功数不够，运营需要看到具体店铺、商品和平台状态。']
    ],
    mechanicsTitle: '多店铺工作流中哪些内容是隔离的',
    mechanics: [['连接', '平台授权和卖家身份只属于一个店铺记录。'], ['数据', 'Product、Offer、Listing 和 Article 都保留平台和店铺信息。'], ['规则', '最低价、最高价和调价设置只作用于选中的商品。'], ['任务', '批量任务和状态记录标明来源店铺和操作类型。']],
    noteTitle: '多店铺管理不等于 ERP',
    note: '调价先锋集中处理调价和相关的 Offer 运营（批量导入导出、库存修改等），不替代订单、仓储、采购、财务或物流系统。',
    workflowTitle: '可审计地添加店铺',
    workflow: [['创建店铺', '先选对平台和店铺身份，再添加授权。'], ['小范围同步', '确认商品和 Offer 身份准确，不依赖模糊匹配。'], ['先筛选再批量', '按店铺、平台、EAN、SKU、状态和规则条件确定目标范围。'], ['看任务结果', '按店铺查看进度和失败原因，而不是只看一句“完成”。']],
    exampleTitle: '一个筛选条件，对应一个清晰的范围', exampleLabel: '运营示例',
    example: '<strong>示例：</strong>运营筛选出 OnBuy 店铺 A 中“未设置最低价”的在售 Listing，批量导入调价规则。这次操作只作用于筛选出的商品，生成一条可追溯的任务，店铺 B 和其他平台完全不受影响。',
    faq: [
      ['一个账号可以管理不同平台的店铺吗？', '可以。工作台统一展示支持的店铺，每个店铺保留自己的授权、数据和平台适配。'],
      ['可以批量设置调价规则吗？', '可以。支持按条件筛选或勾选商品批量操作，也可以通过表格批量导入最低价、最高价等规则。'],
      ['多店铺怎么收费？', '按店铺收费，168 元 / 店铺 / 月，商品数量不限。'],
      ['批量操作失败了怎么排查？', '任务和商品记录会保留店铺、操作和平台返回结果，可以直接定位失败原因。']
    ],
    related: [['欧洲多平台自动调价', '/zh/multi-marketplace-repricing/'], ['自动调价原理', '/zh/features/automatic-repricing/'], ['最低价保护', '/zh/features/min-max-price-rules/']]
  }
];
